# Home: добавление комментария

# from selenium import webdriver
# driver = webdriver.Chrome()
# driver.get('https://practice.automationtesting.in/')
# driver.maximize_window()
# driver.implicitly_wait(5)
# driver.execute_script("window.scrollBy(0, 600);")
# book_btn = driver.find_element_by_css_selector(".post-160")
# book_btn.click()
# driver.execute_script("window.scrollBy(0, 600);")
# revies = driver.find_element_by_css_selector(".reviews_tab")
# revies.click()
# rating = driver.find_element_by_css_selector(".star-5")
# rating.click()
# your_review = driver.find_element_by_id("comment")
# your_review.send_keys("Nice book!")
# name = driver.find_element_by_id("author")
# name.send_keys("Max")
# email = driver.find_element_by_id("author")
# email.send_keys("max@bk.ru")
# submit_btn = driver.find_element_by_css_selector(".submit")
# submit_btn.click()
# driver.quit()